apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-secret
type: Opaque
stringData:
  SECRET_KEY: dev-secret-key
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_HOST: postgres
  DB_NAME: appdb
  DB_USER: appuser
  DB_PASSWORD: apppassword
  DB_PORT: "5432"