django:
  replicaCount: 2

  image:
    repository: k8s-django-app
    tag: v2
    pullPolicy: Never
  
  env:
    debug: "False"
    allowedHosts: "prod.local"

nginx:
  replicaCount: 3

ingress:
  host: prod.local

