apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: k8s-django-app:local
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - python manage.py collectstatic --noinput && gunicorn project.wsgi:application --bind 0.0.0.0:8000
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DEBUG
              value: "False"
            - name: ALLOWED_HOSTS
              value: "django.local"
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: static-files-pvc
