name: Build Push and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            vzh12345/k8s-django-app:${{ github.sha }}

  deploy-dev:
    needs: build-and-push
    runs-on: self-hosted
    if: github.event_name == 'push'

    steps:
      - name: Deploy to dev via Helm
        run: |
          cd ~/projects/k8s-django-app
          helm upgrade my-app ./django-chart -n dev -f values-dev.yaml \
            --set django.image.tag=${{ github.sha }} \
            --set django.image.pullPolicy=IfNotPresent
          k3s kubectl rollout status deployment/my-app-django -n dev
  
  deploy-prod:
    needs: build-and-push
    runs-on: self-hosted
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to prod via Helm
        run: |
          cd ~/projects/k8s-django-app
          helm upgrade my-app ./django-chart -n prod -f values-prod.yaml \
            --set django.image.tag=${{ github.sha }} \
            --set django.image.pullPolicy=IfNotPresent
          k3s kubectl rollout status deployment/my-app-django -n prod